improve doc
- improvements to self documentation in "config/host-sanity-sample.php"
- improve --help messages in "bin/sanity" scripts

diff --git a/bin/sanity/avg-ram-check b/bin/sanity/avg-ram-check
--- a/bin/sanity/avg-ram-check
+++ b/bin/sanity/avg-ram-check
@@ -44,9 +44,8 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 	echo 'exit status meanings:'
 	echo '    3: average ram usage too high'
 	echo '    5: average ram usage above warning threshold'
-	echo '    7: missing dependency'
-	echo '    8: missing expected column header in sar output'
-	echo '    9: unexpected non-numeric column value in sar output'
+	echo '    7: system is missing the "sar" command'
+	echo '    8: parse error while processing "sar" command output'
 	exit 0
 }
 
@@ -160,22 +159,22 @@ MEMFREE=$(echo "$SARAVG" | awk '{print $'$MEMFREECOL'}') || exit
 [ $(expr "x$MEMUSED" : "x[0-9]*$") -gt 0 ] || {
 	>&2 echo "$ME_NAME: unexpected non-numeric output for sar MEMUSED '$MEMUSED'"
   >&2 print_sar_summary
-  exit 9
+  exit 8
 }
 [ $(expr "x$KBUFFER" : "x[0-9]*$") -gt 0 ] || {
 	>&2 echo "$ME_NAME: unexpected non-numeric output for sar KBUFFER '$KBUFFER'"
 	>&2 print_sar_summary
-  exit 9
+  exit 8
 }
 [ $(expr "x$KBCACHE" : "x[0-9]*$") -gt 0 ] || {
 	>&2 echo "$ME_NAME: unexpected non-numeric output for sar KBCACHE '$KBCACHE'"
 	>&2 print_sar_summary
-  exit 9
+  exit 8
 }
 [ $(expr "x$MEMFREE" : "x[0-9]*$") -gt 0 ] || {
 	>&2 echo "$ME_NAME: unexpected non-numeric output for sar MEMFREE '$MEMFREE'"
 	>&2 print_sar_summary
-  exit 9
+  exit 8
 }
 
 #
diff --git a/bin/sanity/reboot-required-check b/bin/sanity/reboot-required-check
--- a/bin/sanity/reboot-required-check
+++ b/bin/sanity/reboot-required-check
@@ -35,6 +35,9 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 #
 [ "$HELP_MODE" = "1" ] && {
 	printf "usage:\n  $ME_NAME $ME_USAGE\n"
+	echo 'exit status meanings:'
+   echo '    3: a reboot is required'
+   echo '    7: unable to determine if reboot is required on this system'
 	exit 0
 }
 
@@ -43,7 +46,7 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 #
 [ -f "/etc/debian_version" ] || {
 	>&2 echo "$ME_NAME: this script only works on debian based distros"
-	exit 1
+	exit 7
 }
 
 #
diff --git a/bin/sanity/security-updates-check b/bin/sanity/security-updates-check
--- a/bin/sanity/security-updates-check
+++ b/bin/sanity/security-updates-check
@@ -35,6 +35,9 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 #
 [ "$HELP_MODE" = "1" ] && {
 	printf "usage:\n  $ME_NAME $ME_USAGE\n"
+	echo 'exit status meanings:'
+   echo '    3: security updates are available'
+   echo '    7: unable to determine if security updates are available on this system'
 	exit 0
 }
 
@@ -43,7 +46,7 @@ shift $((OPTIND-1)) # remove parsed options and args from $@ list
 #
 [ -f "/etc/debian_version" ] || {
 	>&2 echo "$ME_NAME: this script only works on debian based distros"
-	exit 1
+	exit 7
 }
 
 #
diff --git a/bin/sanity/unattended-upgrades-check b/bin/sanity/unattended-upgrades-check
--- a/bin/sanity/unattended-upgrades-check
+++ b/bin/sanity/unattended-upgrades-check
@@ -8,6 +8,7 @@ exit_status_meanings() {
 	echo 'exit status meanings:'
   echo '    3: Update-Package-Lists or Unattended-Upgrade is not enabled'
   echo '    5: AutocleanInterval is not enabled'
+  echo '    7: unable to determine unattended upgrades on this system'
   echo '    9: the unattended-upgrade package is not installed on the system'
   echo '   10: AutocleanInterval exceeds the --autoclean-interval-max value'
   echo '   15: Automatic-Reboot is not enabled'
@@ -25,7 +26,7 @@ usage() {
 	echo '  --autoclean'
   echo '    enforce that the apt config value "APT::Periodic::AutocleanInterval" is not "0"'
   echo '  --autoclean-interval-max=<NUM>'
-  echo '    enforce that the apt config value "APT::Periodic::AutocleanInterval" is less than specified <NUM>'
+  echo '    enforce that the apt config value "APT::Periodic::AutocleanInterval" is <NUM> or lower'
 }
 
 #
@@ -83,7 +84,7 @@ fi
 #
 [ -f "/etc/debian_version" ] || {
 	>&2 echo "$ME_NAME: this script only works on debian based distros"
-	exit 1
+	exit 7
 }
 
 #
